blueprint:
  name: Homematic(IP) reactivate device full
  description: Reactivate every device marked as not available.
    v2022-12-05
  domain: automation
  source_url: https://github.com/danielperna84/custom_homematic/blob/devel/blueprints/automation/homematicip_local_reactivate_device_full.yaml

mode: restart
max_exceeded: silent

trigger:
  - platform: event
    event_type: homematic.device_availability
    event_data:
      unavailable: true

action:
  - service: homematicip_local.force_device_availability
    data:
      device_id: "{{ trigger.event.data.device_id }}"
