blueprint:
  name: Homematic(IP) reactivate device by type
  description: Reactivate a device marked as not available by type.
    v2022-12-05
  domain: automation
  source_url: https://github.com/danielperna84/custom_homematic/blob/devel/blueprints/automation/homematicip_local_reactivate_device_by_type.yaml
  input:
    device_type:
      name: Device Type
      description: The type of the Homematic device. E.g. HmIP-BROLL
      selector:
        text:
          type: text

mode: restart
max_exceeded: silent

trigger:
  - platform: event
    event_type: homematic.device_availability
    event_data:
      device_type: !input device_type
      unavailable: true

action:
  - service: homematicip_local.force_device_availability
    data:
      device_id: "{{ trigger.event.data.device_id }}"
