blueprint:
  name: Homematic(IP) Local Show device error
  description: Display errors emitted by devices
  domain: automation
  source_url: https://github.com/danielperna84/custom_homematic/blob/devel/blueprints/automation/homematicip_local_show_device_error.yaml

mode: restart
max_exceeded: silent

trigger:
- platform: event
  event_type: homematic.device_error

action:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{trigger.event.data.error == true }}'
      sequence:
        - service: persistent_notification.create
          data:
            notification_id: "{{ trigger.event.data.identifier }}"
            title:  "{{ trigger.event.data.title }}"
            message: "{{ trigger.event.data.message }}"
    - conditions:
      - condition: template
        value_template: '{{trigger.event.data.error == false }}'
      sequence:
        - service: persistent_notification.dismiss
          data:
            notification_id: "{{ trigger.event.data.identifier }}"
