blueprint:
  name: Homematic(IP) Local Persistent notification
  description: Display persistent notification if device is not available.
    v2022-12-11
  domain: automation
  source_url: https://github.com/danielperna84/custom_homematic/blob/devel/blueprints/automation/homematicip_local_persistent_notification.yaml

mode: restart
max_exceeded: silent

trigger:
  - platform: event
    event_type: homematic.device_availability

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{trigger.event.data.unavailable == true }}"
        sequence:
          - service: persistent_notification.create
            data:
              notification_id: "{{ trigger.event.data.identifier }}"
              title: "{{ trigger.event.data.title }}"
              message: "{{ trigger.event.data.message }}"
      - conditions:
          - condition: template
            value_template: "{{trigger.event.data.unavailable == false }}"
        sequence:
          - service: persistent_notification.dismiss
            data:
              notification_id: "{{ trigger.event.data.identifier }}"
