# Describes the format for available component services

clear_cache:
  fields:
    entry_id:
      required: true
      selector:
        config_entry:
          integration: homematicip_local

delete_device:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: homematicip_local

export_device_definition:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: homematicip_local

fetch_system_variables:
  fields:
    entry_id:
      required: true
      selector:
        config_entry:
          integration: homematicip_local

force_device_availability:
  fields:
    device_id:
      required: false
      selector:
        device:
          integration: homematicip_local
    device_address:
      example: "0008789453"
      required: false
      selector:
        text:

get_device_value:
  fields:
    device_id:
      required: false
      selector:
        device:
          integration: homematicip_local
    device_address:
      example: "0008789453"
      required: false
      selector:
        text:
    channel:
      required: true
      selector:
        number:
          min: 1
          max: 99
    parameter:
      required: true
      example: STATE
      selector:
        text:

get_paramset:
  fields:
    device_id:
      required: false
      selector:
        device:
          integration: homematicip_local
    device_address:
      example: "0008789453"
      required: false
      selector:
        text:
    channel:
      required: false
      selector:
        number:
          min: 0
          max: 99
    paramset_key:
      required: true
      example: MASTER
      selector:
        text:

set_variable_value:
  fields:
    entry_id:
      required: true
      selector:
        config_entry:
          integration: homematicip_local
    name:
      required: true
      example: "testvariable"
      selector:
        text:
    value:
      required: true
      example: 1
      selector:
        text:

set_device_value:
  fields:
    device_id:
      required: false
      selector:
        device:
          integration: homematicip_local
    device_address:
      example: "0008789453"
      required: false
      selector:
        text:
    channel:
      required: true
      selector:
        number:
          min: 1
          max: 99
    parameter:
      required: true
      example: STATE
      selector:
        text:
    value:
      required: true
      example: 1
      selector:
        text:
    value_type:
      selector:
        select:
          options:
            - "boolean"
            - "dateTime.iso8601"
            - "double"
            - "int"
            - "string"
    wait_for_callback:
      required: false
      selector:
        number:
          min: 0
          max: 600
    rx_mode:
      example: BURST
      selector:
        text:

set_install_mode:
  fields:
    interface_id:
      required: true
      example: Interfaces name from config
      selector:
        text:
    mode:
      default: 1
      selector:
        number:
          min: 1
          max: 2
    time:
      default: 60
      selector:
        number:
          min: 1
          max: 3600
          unit_of_measurement: seconds
    address:
      example: LEQ3948571
      selector:
        text:

put_paramset:
  fields:
    device_id:
      required: false
      selector:
        device:
          integration: homematicip_local
    device_address:
      example: "0008789453"
      required: false
      selector:
        text:
    channel:
      required: false
      selector:
        number:
          min: 0
          max: 99
    paramset_key:
      required: true
      example: MASTER
      selector:
        text:
    paramset:
      required: true
      example: '{"WEEK_PROGRAM_POINTER": 1}'
      selector:
        object:
    wait_for_callback:
      required: false
      selector:
        number:
          min: 0
          max: 600
    rx_mode:
      example: BURST
      selector:
        text:

enable_away_mode_by_calendar:
  target:
    entity:
      domain: climate
      integration: homematicip_local
  fields:
    start:
      required: false
      example: 2022-12-28 14:00
      selector:
        datetime:
    end:
      required: true
      example: 2023-01-28 14:00
      selector:
        datetime:
    away_temperature:
      required: true
      default: 18.0
      selector:
        number:
          min: 4.5
          max: 30.5
          step: 0.5
          mode: slider

enable_away_mode_by_duration:
  target:
    entity:
      domain: climate
      integration: homematicip_local
  fields:
    hours:
      required: true
      default: 6
      selector:
        number:
          min: 1
          max: 999
          step: 1
          mode: slider
    away_temperature:
      required: true
      default: 18.0
      selector:
        number:
          min: 4.5
          max: 30.5
          step: 0.5
          mode: slider

disable_away_mode:
  target:
    entity:
      domain: climate
      integration: homematicip_local

turn_on_siren:
  target:
    entity:
      domain: siren
      integration: homematicip_local
  fields:
    tone:
      example: FREQUENCY_RISING
      required: false
      selector:
        text:
    light:
      example: BLINKING_ALTERNATELY_REPEATING
      required: false
      selector:
        text:
    duration:
      example: 60
      required: false
      selector:
        text:
light_set_on_time:
  target:
    entity:
      domain: light
      integration: homematicip_local
  fields:
    on_time:
      required: true
      selector:
        number:
          min: 1
          max: 8580000
          unit_of_measurement: seconds
          mode: box
switch_set_on_time:
  target:
    entity:
      domain: switch
      integration: homematicip_local
  fields:
    on_time:
      required: true
      selector:
        number:
          min: 1
          max: 8580000
          unit_of_measurement: seconds
          mode: box
set_cover_combined_position:
  target:
    entity:
      domain: cover
      integration: homematicip_local
      device_class: blind
  fields:
    position:
      required: true
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
    tilt_position:
      required: false
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
    wait_for_callback:
      required: false
      selector:
        number:
          min: 0
          max: 600
update_device_firmware_data:
  fields:
    entry_id:
      required: true
      selector:
        config_entry:
          integration: homematicip_local
