name: "Test-Run"

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - "dev**"
      - devel
      - master
  pull_request: ~
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - name: Set Timezone
        uses: szenius/set-timezone@v1.1
        with:
          timezoneLinux: "Europe/Berlin"
          timezoneMacos: "Europe/Berlin"
          timezoneWindows: "Europe/Berlin"
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_test.txt
      - name: Run tests and collect coverage
        run: pytest --cov=custom_components tests --asyncio-mode=legacy
